name: 'Release Docker'

on:
  push:
    branches:
      - version-14-hotfix

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  docker-release:
    name: 'Trigger Docker build on release'
    runs-on: ubuntu-latest
    steps:
      - id: docker
        run: |
          if [[ '${{ github.event_name }}' == 'pull_request' ]]; then
            DOCKER_TAG="pr-${{ github.event.number }}"
          else
            DOCKER_TAG="gh-${{ github.run_id }}"
          fi
          echo "DOCKER_TAG: ${DOCKER_TAG}"
          echo "gh-docker-tag=${DOCKER_TAG}" >> $GITHUB_OUTPUT
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: bacsicayxanh-hcm/frappe-docker
          event-type: build-docker
          client-payload: '{"ref": "main", "gh-docker-tag": "${{ steps.docker.output .gh-docker-tag }}"}'
