name: 'Release Docker'

on:
  push:
    branches:
      - version-14-hotfix

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  docker-release:
    name: 'Trigger Docker build on release'
    runs-on: ubuntu-latest
    permissions:
      contents: none
    container:
      image: alpine:latest
    steps:
    - name: curl
      run: |
        apk add curl bash
        curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer ${{ secrets.CI_PAT }}" https://api.github.com/repos/bacsicayxanh-hcm/frappe_docker/actions/workflows/build_docker.yml/dispatches -d '{"ref":"main"}'
