name: 'Release Docker'

on:
  push:
    branches:
      - version-14-hotfix
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker-release:
    name: 'Trigger Docker build on release'
    runs-on: ubuntu-latest
    steps:
      - id: variable
        run: |
          if [[ '${{ github.event_name }}' == 'pull_request' ]]; then
            DOCKER_TAG="pr-${{ github.event.number }}"
          else
            DOCKER_TAG=`echo ${GITHUB_SHA} | cut -c1-8`
          fi
          echo "DOCKER_TAG: ${DOCKER_TAG}"
          echo "gh-docker-tag=${DOCKER_TAG}" >> $GITHUB_OUTPUT
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: bacsicayxanh-hcm/frappe_docker
          event-type: build-docker
          client-payload: '{"ref": "main", "gh-docker-tag": "${{ steps.variable.outputs.gh-docker-tag }}", "frappe-version": "${{ steps.variable.outputs.branch }}"}'
